### ISSUE TITLE
Schema checks on open

### ISSUE THREAD

**Issue by pwnall** [WICG/kv-storage#41]
I'd like the lazy database open process to validate the schema on success. Non-trivial (to me) observation: the schema cannot change while the database connection is open, so the open check guarantees no future errors. Proposed checks below.

Database contains the correct object store:
* `objectStoreNames.indexOf('store') !== -1`
* `objectStoreNames.length === 1`

The object store has the correct schema:
* `objectStore('store').autoIncrement === false`
* `objectStore('store').keyPath === null`
* `objectStore('store').indexNames.length === 0`

The main goal here is to avoid having to reason about how the API behaves when pointed at an IndexedDB instance that "mostly" matches the needed schema. Allowing other object stores is mostly harmless, while indexes can make things more complicated. I'd rather that this API starts out strict in this respect, and we relax the constraints here if there are demonstrated use cases.

Note that the proposal here doesn't restrict the upgrade path -- apps are free to switch to full IndexedDB and change the database schema. It simply says that this API will refuse to operate on a "custom" database.

**Comment by domenic** [comment]
This is a super-great idea! Really glad you brought this up.
