### ISSUE TITLE
Consider to make async local storage a proper web API

### ISSUE THREAD

**Issue by smaug----** [WICG/kv-storage#43]
Since, IMO, the API should be considered as a replacement for localStorage, it should be defined in the same way and be as simple as possible to use.
Even small things, like import { storage } from "std:async-local-storage";, make it harder.

Backend of the API could or should be IndexedDB.

Also, if it wasn't a layered API, it wouldn't depend on whatever happens to the layered API concept in general.

**Comment by domenic** [comment]
I'm unclear what concrete changes you'd like to the spec text here. Could you point to some?

One thing I see is that you seem to prefer not using built-in modules, and instead continue using globals. We'd like to start using modules for new features, and have some general buy-in from multiple parties; /cc @lukewagner in particular from the Mozilla side.

Otherwise, what spec changes would you propose?

(Note, the word "layered API" doesn't appear anywhere in the spec text.)

**Comment by smaug----** [comment]
I'd rather explicitly not use async local storage as an example for using modules. We want some better behaving replacement for localStorage, so the API usage should be as close to that as possible (but be async). Requiring one to familiarize with built-in modules is just extra overhead there.

(also, from implementation point of view, relying on webidl would probably ease creating a fast implementation. Implementation detail, sure, but both ease of implementation and performance matter.)

**Comment by domenic** [comment]
I've created a separate issue to discuss switching to Web IDL in https://github.com/heycam/webidl/issues/580.

**Comment by felixfbecker** [comment]
I think one of JS's beauties is that the stdlib is easily discoverable by invoking autocomplete in the global scope. It's super easy to invoke them in the dev console too.

Part of what makes `localStorage` so simple is that you can just call (read, write, inspect) it from anywhere. If we want to a worthy successor that keeps the simplicity (which is a stated goal, or we could just use IndexedDB directly) imo it should be a global too. If it's tucked away behind a module, there is additional friction to discover and use it compared to `localStorage`.

**Comment by pwnall** [comment]
From an implementation perspective -- piling everything into the global namespace isn't free. Glossing over many details, every new feature adds a tiny overhead to creating a new tab. CPUs aren't getting any faster, so we can't afford to keep paying this overhead. We need a sustainable way of evolving the Web platform. So, I think we should give modules a try.

Putting features in modules doesn't need to prevent autocomplete. When I use Eclipse to write Java, auto-complete suggestions include classes that haven't been imported yet. Selecting the suggestions automatically adds the correct import statements. I trust that we can evolve our tools to get to that point.
