### ISSUE TITLE
area.backingStore !== area.backingStore

### ISSUE THREAD

**Issue by domenic** [WICG/kv-storage#45]
As specified, https://wicg.github.io/kv-storage/#storagearea-backingstore returns a new object each time. This is a bad thing---indeed, it's something I often correct other peoples' specs about.

Options:

- Cache the object the first time it's returned. (Or, equivalently in spec land, create it on `StorageArea` creation.)
- Change to a `.backingStore()` or `.getBackingStore()` method.
- Split into individual properties, e.g. `area.backingDatabase`, `area.backingStore` (`backingObjectStore`?), `area.backingDatabaseVersion`.

Thoughts welcome; not sure which way I'm leaning right now.

**Comment by domfarolino** [comment]
FWIW I definitely less of a fan of the third option due to it not being as "simple". I like the idea of caching the object though.

**Comment by developit** [comment]
If we cache the returned backingStore object, can we make sure it's a frozen object?  I'm worried folks will mutate it and rely on it being a cached reference.

**Comment by jakearchibald** [comment]
Out of the choices, I prefer the first option. We don't freeze many objects, but I'm not against it.

Alternatively, just provide the database name. You can open the database without a version number, which will just open the latest version. Then, you can get the version number and object store name(s).

**Comment by domenic** [comment]
The first option seems the least "webby" to me (partially because it's hard to express in Web IDL), but it seems like all the web devs I talk to and get to weigh in on this thread prefer that, so probably I'll go in that direction. Thanks so much all!

**Comment by jakearchibald** [comment]
Example:

```js
const request = indexedDB.open(kvStorage.dbName);
request.addEventListener('success', () => {
  const db = request.result;
  const { version } = db;
  const [ storeName ] = db.objectStoreNames;
  // …
});
```
