### ISSUE TITLE
Async parsing like Cloudflare KV API

### ISSUE THREAD

**Issue by manobi** [WICG/kv-storage#50]
Cloudflare Workers have a very similar API to persist data from their Workers (service workers running on their CDN with VM isolates).
https://developers.cloudflare.com/workers/kv/api

Their docs say you can pass the "type" of data you are retrieving with ".get" method:
```
NAMESPACE.get(key, [type])
```

I'm not sure if they actually do that, but wouldn't it be nice if you do something like this and get async JSON.parse out of the box ?
```
storage.get(key, 'json');
```

I know nothing about browsers JSON.parse implementation or if this could be implemented.

**Comment by domenic** [comment]
This doesn't seem to add a lot versus just using `JSON.parse(await storage.get(key))`. Or, better yet, just send your data to `storage.set()` without serializing it to a string, and then you won't need to re-parse it on the way back out.

Can you clarify more what use case is not addressed by the current API?

**Comment by manobi** [comment]
If we have a very huge json value stored, I imagine the string to object conversion could be handle out of the main thread.

With your example the access to key's value would asynchronous but the parsing synchronous right?

```
| blocking | idle   |
JSON.parse(await storage.get(key))
```

The implementation of what I'm purposing would be something like it:
```
| idle           |     idle           | blocking                       |
storage.get(key).then(JSON.parseAsync).then(data => data.map(item => item.name))
```

**Comment by manobi** [comment]
> Or, better yet, just send your data to storage.set() without serializing it to a string, and then you won't need to re-parse it on the way back out.

Wow the repo readme did not talk about it, now that I've seen the examples in https://wicg.github.io/kv-storage not sure if I would ever store a JSON string.

Thanks for the clarifications, now I'm convinced that Cloudflare must implement this design instead.

**Comment by domenic** [comment]
OK, sounds like this is best handled by not serializing :). Will close, but feel free to continue discussing!
