### ISSUE TITLE
README incorrectly refer to AngularJS as Angular

### ISSUE THREAD

**Issue by trotyl** [WICG/kv-storage#54]
At the end of [README.md](https://github.com/WICG/kv-storage/blob/master/README.md), it's saying:

> For comparison, Angular is downloaded [~313K times per week](https://www.npmjs.com/package/angular), React [~2.807 million times per week](https://www.npmjs.com/package/react), and Vue [~436K times per week](https://www.npmjs.com/package/vue).

But the link of ["Angular"](https://angular.io/) is the ["AngularJS"](https://angularjs.org/) npm package.

As per [Google's](https://blog.angularjs.org/2017/01/branding-guidelines-for-angular-and.html) [guidelines](https://angular.io/presskit), "Angular" and "AngularJS" are different products in branding.

It should either refer to [Angular's npm package](https://www.npmjs.com/package/@angular/core) or change the name to "AngularJS".

**Comment by domenic** [comment]
A pull request fixing this up would be quite welcome!
