### ISSUE TITLE
Cross browser compatibility

### ISSUE THREAD

**Issue by kevb10** [WICG/kv-storage#59]
So obviously, this will be in Chrome and I'm assuming that any changes made to *KV Storage* will also ship with any Chrome update. 
What about other browsers? Will any update made be forced to be pushed by other browsers? Could that cause any conformity and compatibility issues? Cause what if one feature is available in Chrome but not in Firefox or IE?

**Comment by domenic** [comment]
I'm a little confused by this issue. KV storage is a web platform specification, and every browser chooses when and how to implement the specification. In general all browsers try their best to stay up to date with any changes, but rarely do changes launch at the same time in all browsers. This leads to the usual web platform development practices like feature testing, polyfills, etc.

There's certainly no way for spec authors to "force push" updates to their spec into the implementation code of browsers.

Does this help?

**Comment by domenic** [comment]
Closing, but please let us know if there's more you'd like to discuss!
