### ISSUE TITLE
Can't we use web workers for Async access to LS

### ISSUE THREAD

**Issue by Kitanga** [WICG/kv-storage#61]
I thought we could have "Async" access to local storage using web worker?

**Comment by domenic** [comment]
I'm not sure what this question is asking exactly. One interpretation is, "will KV storage work in web workers"? The intention is yes.

**Comment by Kitanga** [comment]
I'm more curious as to whether this is even necessary, since, from my
understanding, we can use web workers to access local storage
asyncronously. Do we need yet another API for this?

**Comment by domenic** [comment]
Ah, no, localStorage is not available in workers; it is only exposed on Window global objects. This is partly to avoid the spread of the bad, legacy programming model (synchronous I/O) that localStorage encourages.

**Comment by Kitanga** [comment]
Well there's a shocker, but makes sense. Thanks for clarifying though.
