### ISSUE TITLE
Derive from %AsyncIteratorPrototype%?

### ISSUE THREAD

**Issue by Ms2ger** [WICG/kv-storage#65]
For the storage area async iterator prototype object.

https://wicg.github.io/kv-storage/#async-iterator

**Comment by domenic** [comment]
Oh, wow, yeah, that's just a spec bug. Thank you for catching.

**Comment by domenic** [comment]
Tests already test this: https://github.com/web-platform-tests/wpt/blob/master/kv-storage/keys-values-entries.https.html
