### ISSUE TITLE
Name is unclear

### ISSUE THREAD

**Issue by litherum** [WICG/kv-storage#69]
“kv” is an acronym, and is not significantly easier to say/read than “key value”. In particular, non-native English speakers may find this name confusing.

For comparison, consider if semaphores were called “pv-coordination”.

**Comment by domenic** [comment]
Thanks for filing the issue! The intent here is specifically to distinguish it from other key/value storage APIs, by giving it a term of art. In particular, contrast IndexedDB (a term of art) with indexed databases (a general concept).

See previous discussion in #38, where we arrived at this.

Do you think we should add something to the spec or explainer talking about this choice?

**Comment by domenic** [comment]
Closing for now, but happy to add something to the spec or explainer if you think it'd be helpful!
