### ISSUE TITLE
feature-request - add appendFile-like capability to overcome nedb performance-bottleneck

### ISSUE THREAD

**Issue by kaizhu256** [WICG/kv-storage#73]
something like `append(key, value)` would be nice-to-have for single-file, log-based database like nedb.

when in browser, nedb emulates appendFile by re-saving its entire database as a blob to indexedb whenever a row insert/delete/update is performed [1]. this performance-hit makes it less-practical for write-persisting largish datasets (> 20mb):

```js
/*
 * [1] nedb emulates appendFile inefficiently in browser
 * https://github.com/louischatriot/nedb/blob/v1.6.0/browser-version/browser-specific/lib/storage.js#L49
 */

function appendFile (filename, toAppend, options, callback) {
  // Options do not matter in browser setup
  if (typeof options === 'function') { callback = options; }

  localforage.getItem(filename, function (err, contents) {
    contents = contents || '';
    contents += toAppend;
    localforage.setItem(filename, contents, function () { return callback(); });
  });
}
```

**Comment by domenic** [comment]
I'm not quite sure I understand this. In particular, what IndexedDB operations do you suggest this maps to?

**Comment by kaizhu256** [comment]
there is no existing IndexedDB operation to "append" data to an entry.  this would be a new operation in kv-storage, for example:

```js
// persist nedb as logfile
tx.objectStore(store).add("nedb", "");
// log set-operation to table1
tx.objectStore(store).append("nedb", 'table1 set { "id": 1, "field1": "foo", "field2": "bar" }\n');
// log set-operation to table1
tx.objectStore(store).append("nedb", 'table1 set { "id": 2, "field1": "baz", "field2": "quz" }\n');
// log delete-operation to table1
tx.objectStore(store).append("nedb", 'table1 delete { "id": 1 }\n');

...

// restart browser, and restore nedb by replaying logfile
var logfile = tx.objectStore(store).get("nedb");
var myDb = replay(logfile);
// myDb = { table1: [{id: 2, field1: "baz", field2: "qux"}] }
```

because IndexedDB has no `append` feature, nedb currently has to inefficiently `set` the entire logfile for write-persists.

**Comment by domenic** [comment]
Ah, OK. Since KV Storage is just a higher-level interface on top of IndexedDB, I think you'd be best off opening the issue on the IndexedDB specification instead: https://github.com/w3c/IndexedDB/issues/. It's not within scope here to add things which are impossible to accomplish with IndexedDB.

Closing, but happy to continue discussing in the closed thread!

**Comment by kaizhu256** [comment]
ok, thx for clarifying scope of kv-storage as just mapping of indexeddb.
