### ISSUE TITLE
Query on implementation status

### ISSUE THREAD

**Issue by SubhamoyS** [WICG/kv-storage#76]
Hello,

I am trying to understand the utility and/or importance of implementing kv-storage for Firefox. It has been some time since the [intent to prototype](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/suT7pB2M9L0/ZuA8AQz6DgAJ) and I would love to know if this is still being actively pursued in the Chromium project.

Thanks in advance!

**Comment by domenic** [comment]
Hi, thanks for reaching out. At this point, due to a combination of [concerns over built-in modules](https://github.com/w3ctag/design-reviews/issues/421#issuecomment-561705979) and a shifting of the Storage team's priorities, Chromium is no longer pursuing KV Storage.

I will work on shutting down the repository to make this more clear.

**Comment by domenic** [comment]
I've removed the usage of built-in modules from this repository, and added a note saying

> Work on this specification is currently suspended, as no browser teams (including the Chromium project, which originated the proposal) are currently indicating interest in implementing it.

Let me know if Mozilla is interested in taking this up, and I can change the wording. I'd be happy to give you or other Mozilla engineers access to the repository if they want to take up the project!

**Comment by asutherland** [comment]
My impression of rough consensus at TPAC suggested that the plan would be to try and fold the API design of KV-storage into IndexedDB as its long-desired promise-based API, so I think the work might just happen there?  (Not that such a thing would happen immediately.)

**Comment by annevk** [comment]
cc @inexorabletash
